[server]
headless = true
enableXsrfProtection = false
enableCORS = false
address = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "#9D8FFF"
backgroundColor = "#0C0A14"
secondaryBackgroundColor = "#17132B"
textColor = "#EAE8F7"
font = "sans serif"
